Repository Canard-Ecarlate/Frontend, pull requests merged in 2022-02, with the labels that each got.

#53 17 Interface jouer
  Assets/Placeholders.meta
  Assets/Placeholders/backCard.png
  Assets/Placeholders/backCard.png.meta
  Assets/Placeholders/bombCard.png
  Assets/Placeholders/bombCard.png.meta
  Assets/Placeholders/chat.PNG
  Assets/Placeholders/chat.PNG.meta
  Assets/Placeholders/defaultBG.png
  Assets/Placeholders/defaultBG.png.meta
  Assets/Placeholders/duckLookLeft.png
  Assets/Placeholders/duckLookLeft.png.meta
  Assets/Placeholders/duckLookRight.png
  Assets/Placeholders/duckLookRight.png.meta
  Assets/Placeholders/gameBg.jpg
  Assets/Placeholders/gameBg.jpg.meta
  Assets/Placeholders/greenCard.png
  Assets/Placeholders/greenCard.png.meta
  Assets/Placeholders/hiddenDuck.png
  Assets/Placeholders/hiddenDuck.png.meta
  Assets/Placeholders/hideShowEye.png
  Assets/Placeholders/hideShowEye.png.meta
  Assets/Placeholders/menu.PNG
  Assets/Placeholders/menu.PNG.meta
  Assets/Placeholders/progressBar.png
  Assets/Placeholders/progressBar.png.meta
  Assets/Placeholders/turnShower.png
  Assets/Placeholders/turnShower.png.meta
  Assets/Placeholders/yellowCard.png
  Assets/Placeholders/yellowCard.png.meta
  Assets/Plugins/Microsoft.Extensions.Primitives.dll.meta
  Assets/Plugins/Newtonsoft.Json.dll
  Assets/Plugins/Newtonsoft.Json.dll.meta
  Assets/Scenes/GameScene.unity
  Assets/Scenes/GameScene.unity.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts.meta
  Assets/Scripts/.idea/.idea.Scripts.dir/.idea/.gitignore
  Assets/Scripts/.idea/.idea.Scripts.dir/.idea/indexLayout.xml
  Assets/Scripts/.idea/.idea.Scripts.dir/.idea/vcs.xml
  Assets/Scripts/GameSceneScript.cs
  Assets/Scripts/GameSceneScript.cs.meta
  Assets/Test.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TagManager.asset
  ProjectSettings/TimelineSettings.asset
  UserSettings/AndroidLogcatSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: Interface

#63 17 Interface jouer
  Assets/Placeholders/Biberon.PNG
  Assets/Placeholders/Biberon.PNG.meta
  Assets/Scenes/GameScene.unity
  Assets/Scripts/GameSceneScript.cs
  ProjectSettings/TagManager.asset
Labels: Interface, Frontend

#64 17 Interface jouer
  Assets/Placeholders/boomerangg.png
  Assets/Placeholders/boomerangg.png.meta
  Assets/Scenes/GameScene.unity
  Assets/Scripts/GameSceneScript.cs
  ProjectSettings/EditorBuildSettings.asset
  UserSettings/AndroidLogcatSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: Interface, Frontend

#73 10 Interface création salle privée V1 AND 15 Interface rejoindre une salle privée V1
  Assets/Placeholders/backButton.png
  Assets/Placeholders/backButton.png.meta
  Assets/Placeholders/createBg.png
  Assets/Placeholders/createBg.png.meta
  Assets/Placeholders/join.png
  Assets/Placeholders/join.png.meta
  Assets/Placeholders/minus.png
  Assets/Placeholders/minus.png.meta
  Assets/Placeholders/plus.png
  Assets/Placeholders/plus.png.meta
  Assets/Placeholders/privateBg.png
  Assets/Placeholders/privateBg.png.meta
  Assets/Placeholders/publicBg.jpg
  Assets/Placeholders/publicBg.jpg.meta
  Assets/Placeholders/toCreate.jpg
  Assets/Placeholders/toCreate.jpg.meta
  Assets/Placeholders/toPrivate.png
  Assets/Placeholders/toPrivate.png.meta
  Assets/Placeholders/toPublic.jpg
  Assets/Placeholders/toPublic.jpg.meta
  Assets/Scenes/FolderScene.unity
  Assets/Scenes/FolderScene.unity.meta
  Assets/Scenes/GameScene.unity
  Assets/Scripts/GameSceneScript.cs
  Assets/Scripts/Script_Folder.cs
  Assets/Scripts/Script_Folder.cs.meta
  Assets/Scripts/Script_Game.cs
  Assets/Scripts/Script_Game.cs.meta
  ProjectSettings/EditorBuildSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: Interface, Frontend

#74 10 Interface création salle privée V1 AND 15 Interface rejoindre une salle privée V1
  Assets/Scenes/FolderScene.unity
  Assets/Scenes/HomeScene.unity
  Assets/Scripts/FolderScene.cs
  Assets/Scripts/FolderScene.cs.meta
  Assets/Scripts/GameScene.cs
  Assets/Scripts/GameScene.cs.meta
  Assets/Scripts/HomeScene.cs
  UserSettings/EditorUserSettings.asset
Labels: Interface, Frontend

#79 4 Interface salle d'attente
  Assets/Placeholders/Canard-barbarie.png
  Assets/Placeholders/Canard-barbarie.png.meta
  Assets/Placeholders/Canard-blanc.png
  Assets/Placeholders/Canard-blanc.png.meta
  Assets/Placeholders/Canard-col-vert.png
  Assets/Placeholders/Canard-col-vert.png.meta
  Assets/Placeholders/Canard-drogue.png
  Assets/Placeholders/Canard-drogue.png.meta
  Assets/Placeholders/Canard-orange.png
  Assets/Placeholders/Canard-orange.png.meta
  Assets/Placeholders/Canard-plastique.png
  Assets/Placeholders/Canard-plastique.png.meta
  Assets/Placeholders/Obanard.png
  Assets/Placeholders/Obanard.png.meta
  Assets/Placeholders/playButton.png
  Assets/Placeholders/playButton.png.meta
  Assets/Placeholders/toPublic.jpg
  Assets/Scenes/BarScene.unity
  Assets/Scenes/BarScene.unity.meta
  Assets/Scenes/FolderScene.unity
  Assets/Scenes/GameScene.unity
  Assets/Scripts/BarScene.cs
  Assets/Scripts/BarScene.cs.meta
  Assets/Scripts/EndgameScene.cs
  Assets/Scripts/FolderScene.cs
  Assets/Scripts/LoginSignupScene.cs
  Assets/Textures/Backgrounds/barBg.jpg
  Assets/Textures/Backgrounds/barBg.jpg.meta
  Assets/Textures/Buttons/backButton.png
  Assets/Textures/Buttons/backButton.png.meta
  Assets/Textures/Buttons/info.png
  Assets/Textures/Buttons/info.png.meta
  Assets/Textures/Buttons/leaveButton.png
  Assets/Textures/Buttons/leaveButton.png.meta
  ProjectSettings/EditorBuildSettings.asset
  UserSettings/AndroidLogcatSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: Interface, Frontend

#90 SignalR functions
  Assets/CustomHandlers/OnClickHandler.cs.meta~Fix inscription.meta
  Assets/CustomHandlers/OnClickHandler.cs.meta~refs.meta
  Assets/CustomHandlers/OnClickHandler.cs.meta~refs/remotes.meta
  Assets/CustomHandlers/OnClickHandler.cs.meta~refs/remotes/origin.meta
  Assets/Models/Game.cs
  Assets/Models/Game.cs.meta
  Assets/Models/GameDto.cs
  Assets/Models/GameDto.cs.meta
  Assets/Models/ICard.cs
  Assets/Models/ICard.cs.meta
  Assets/Models/IRole.cs
  Assets/Models/IRole.cs.meta
  Assets/Models/NbEachCard.cs
  Assets/Models/NbEachCard.cs.meta
  Assets/Models/NbEachRole.cs
  Assets/Models/NbEachRole.cs.meta
  Assets/Models/OtherPlayerDto.cs
  Assets/Models/OtherPlayerDto.cs.meta
  Assets/Models/Player.cs
  Assets/Models/Player.cs.meta
  Assets/Models/PlayerInWaitingRoomDto.cs
  Assets/Models/PlayerInWaitingRoomDto.cs.meta
  Assets/Models/PlayerMeDto.cs
  Assets/Models/PlayerMeDto.cs.meta
  Assets/Models/RoomConfiguration.cs
  Assets/Models/RoomConfiguration.cs.meta
  Assets/Models/RoomCreationDto.cs
  Assets/Models/RoomCreationDto.cs.meta
  Assets/Models/RoomDto.cs
  Assets/Models/RoomDto.cs.meta
  Assets/Models/User.cs
  Assets/Models/WebCommunicator.cs
  Assets/Scenes/FolderScene.unity
  Assets/Scripts/BarScene.cs
  Assets/Scripts/FolderScene.cs
  Assets/Scripts/HomeScene.cs
  Assets/Scripts/LoginSignupScene.cs
  Assets/Utils/DuckCityHub.cs
  Assets/Utils/DuckCityHub.cs.meta
  Assets/Utils/GlobalVariable.cs
  UserSettings/EditorUserSettings.asset
Labels: Improvement, Frontend
